# Generated by Django 3.2.14 on 2022-07-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.CharField(max_length=300, verbose_name='Краткое описание'),
        ),
    ]
