# Generated by Django 4.1 on 2022-08-04 14:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_image_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='index_num',
        ),
        migrations.AlterField(
            model_name='image',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Длинное описание'),
        ),
    ]
