# Generated by Django 4.1 on 2022-08-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order'], 'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='my_order',
            new_name='order',
        ),
    ]
