# Generated by Django 4.1 on 2022-08-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_image_options_rename_my_order_image_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='placeId',
        ),
    ]
